### ISSUE TITLE
RTSP(S) streams not respecting configured IP address

### ISSUE THREAD

**Issue by chrisbertsch** [briis/unifiprotect#360]
### Home Assistant Version?

2021.11.5

### UniFi Protect Version?

1.20.0

### UniFi Protect HA Integration version?

0.10.0

### What happened?

Previously with version 0.9.1 the RTSP(S) URLs used the host/IP address that was configured when the integration was added. It now appears the integration in version 0.10.0 uses the IP address from UniFi Protect RTSP(S) URLs and no longer respects the configured IP address.

The use case for me is that I have a dedicated IoT network which Home Assistant runs on with all of my IoT devices. I have a UDM-Pro with network interfaces on both the LAN and IoT networks. The URL for RTSP(S) always show the LAN IP address in UniFi Protect despite UniFi Protect binding and being available on all(non WAN) network interfaces on the UDM-Pro. I configure the integration to use the IoT IP address which works fine for everything except the RTSP(S) streams. My goal is to keep all the traffic local to the IoT network for performance and to not traverse the firewall to go to the LAN for RTSP(S) streams.

I did not see this change as a breaking change in the release notes for version 0.10.0 so filing this as a bug. I can also understand this being an advance use case and becoming a feature request. I think separate IoT networks is becoming more common for untrusted IoT devices. So if this was to become a feature request having a checkbox to override the IP address for RTSP(S) streams provided by UniFi Protect and to use the IP address configured for the integration.

**Comment by AngellusMortis** [comment]
This change was to fix the inverse issue if you had your protect instance behind a reverse proxy to prevent HA from trying to connect to the reverse proxy host for RTSP. 

That being said, it _should_ be fixed in the 0.11 branch. When I added the connection_host stuff for 0.10, I just did a fast implementation instead of the full one that is in the new API client that 0.11 will use. That API client will resolve the DNS name and then pick the IP that matches the IP address you configured _if_ it is in the list of _all_ connection hosts. The 0.10 one _always_ uses the default connection host (which for a UDM Pro is 192.168.1.1 or the default LAN).

The WIP PR for the 0.11 stuff (if you would like to manually pull down the branch and test it): https://github.com/briis/unifiprotect/pull/354

Changelog for the branch: https://github.com/briis/unifiprotect/blob/ac5b039953000d11f37731e96f4a826e5ddd1469/CHANGELOG.md

**Comment by chrisbertsch** [comment]
Thanks for the quick replay. I just tested with the branch protectapi but still seeing stream_worker errors in the logs trying to connect to the LAN IP address. Does it have to be a DNS name if so I can do that but for now I have just been using IP addresses?

**Comment by AngellusMortis** [comment]
Nope. Here is the logic: https://github.com/briis/pyunifiprotect/blob/master/pyunifiprotect/api.py#L489

`_host` = the value passed to HA.
`self.bootstrap.nvr.hosts` = `<protect>/proxy/protect/api/nvr` -> `hosts`

**Comment by chrisbertsch** [comment]
Looking at the logic at https://github.com/briis/pyunifiprotect/blob/master/pyunifiprotect/api.py#L496. Is this comparing a string and a IPv4Address? If so I think this will always return False? I assume self.bootstrap.nvr.hosts is a list of strings as found via /proxy/protect/api/bootstrap.

```python
from ipaddress import IPv4Address
test1 = IPv4Address("192.168.2.1")
test2 = "192.168.2.1"
test1 == test2
```

**Comment by AngellusMortis** [comment]
They are converted to `IPv4Address` addresses after they are loaded from the JSON.

https://github.com/briis/pyunifiprotect/blob/master/pyunifiprotect/data/nvr.py#L451

**Comment by AngellusMortis** [comment]
I thought I had a test to verify the logic, but it looks like I do not.

**Comment by chrisbertsch** [comment]
@AngellusMortis is this expected to work with pyunifiprotect v1.0.4? If so I will remove the home assistant integration from the equation and test directly with pyunifiprotect v1.0.4.

**Comment by AngellusMortis** [comment]
Sorry, I never wrote that test. let me do that now. 

And yeah, it should work in 1.0.4, but you need to use `ProtectApiClient`, not `UpvServer`.

**Comment by AngellusMortis** [comment]
I was wrong before; I did have a test. but I still made the test better and more explicit. So, it _should_ be working in HA in 0.11

Test: https://github.com/briis/pyunifiprotect/blob/master/tests/test_api.py#L153
Test passing: https://github.com/briis/pyunifiprotect/actions/runs/1518915553

If you want to test it out manually:
```bash
pip install pyunifiprotect[shell]
unifi-protect shell -U username -P password -a address -p port # unifi-protect shell --help for more details
```
```python
protect_client._host # should = the `address` param you passed in
protect_client.bootstrap.nvr.hosts # list of possible connection hosts for RTSP
protect_client.connection_host # should = the `address` param you passed in if the IP resolves to one of the ones in the above list
```

**Comment by chrisbertsch** [comment]
It appears the unifi-portect shell uses UpvServer instead of ProtectAPIClient?

Though I was able to verify the RTSP and RTSPS URLs are correct with pyunifiprotect 1.2.0 with ProtectAPIClient directly.

**Comment by AngellusMortis** [comment]
You have to pass `-n` to get `ProtectApiClient`. Also, the HA version with `ProtectApiClient` is on master right now if you really want to try it out. We should be cutting a 0.11 beta tomorrow as long as nothing horribly goes wrong.

**Comment by AngellusMortis** [comment]
0.11 beta is out now if you can test it to see if RTSP works for you now.

**Comment by chrisbertsch** [comment]
I can confirm this is now working in v0.11.0-beta.1.

**Comment by AngellusMortis** [comment]
Going to go ahead and close this then. Thanks for verifying.
